services:
  - type: web
    name: oh-my-wash-server
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: SQUARE_ACCESS_TOKEN
        sync: false
      - key: SQUARE_LOCATION_ID
        sync: false
      - key: SQUARE_APPLICATION_ID
        sync: false
      - key: SQUARE_APPLICATION_SECRET
        sync: false
